# -*- coding: utf-8 -*-
"""Breast Cancer Diagnosis ANN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5UWvhyolWnS7PvIE5znhJo4qfcufwHX
"""

import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import relu, sigmoid
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

data = pd.read_csv('Breast Cancer Diagnosis Dataset.csv')
data = data.drop(['Unnamed: 32', 'id'],axis=1)
#data['diagnosis'] = pd.get_dummies(data['diagnosis'], drop_first=True)
#data['diagnosis'] = data['diagnosis'].map({'B':0, 'M':1})

sns.countplot(x='diagnosis', data=data)
plt.title('Distribution of Diagnosis (Malignant vs Benign)')
plt.show()

labelencoder = LabelEncoder()
data['diagnosis'] = labelencoder.fit_transform(data['diagnosis'])
data

x = data.drop('diagnosis', axis=1)
y = data['diagnosis']

X_train, X_test, Y_train, Y_test = train_test_split(x, y, random_state=42, test_size=0.2)

model = Sequential([
    Dense(units=128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(units=64, activation='relu'),
    Dense(units=32, activation='relu'),
    Dense(units=1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

class MyCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if logs.get('accuracy') >= 0.9629:
            print("\nReached the desired accuracy, stopping training!")
            self.model.stop_training = True
callbacks = MyCallback()

model.fit(X_train, Y_train, epochs=100, callbacks=[callbacks])

y_pred = model.predict(X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
print(y_pred_binary )

accuracy = accuracy_score(Y_test, y_pred_binary)
print(f'Accuracy: {accuracy}')